# COMMITIZEN CUSTOM VALIDATION
# vi" syntax=toml
# https"//commitizen-tools.github.io/commitizen/customization/

[tool.commitizen]
name = "cz_customize"

[tool.commitizen.customize]
info              = "This is customized info"
example           = "feature: this feature enable customize through config file"
schema            = "<type>: <body>"
bump_map          = {"break" = "MAJOR", "new" = "MINOR", "fix" = "PATCH", "hotfix" = "PATCH"}
info_path         = "cz_customize_info.txt"
bump_pattern      = "^(break|new|fix|hotfix)"
schema_pattern    = "(feature|bug fix):(\\s.*)"
message_template  = ":{{ change_type }}: {{ message }}"
change_type_order = ["BREAKING CHANGE", "feat", "fix", "refactor", "perf"]

[[tool.commitizen.customize.questions]]
type    = "input"
name    = "message"
message = "Write the message body"

[[tool.commitizen.customize.questions]]
type    = "list"
name    = "change_type"
choices = [  # https"//gitmoji.dev/
  { value = "art",                       name = "ğŸ¨ Improving structure / format of the code."    },
  { value = "zap",                       name = "âš¡ï¸ Improving performance."                        },
  { value = "fire",                      name = "ğŸ”¥ Removing code or files."                      },
  { value = "bug",                       name = "ğŸ› Fixing a bug."                                },
  { value = "ambulance",                 name = "ğŸš‘ Critical hotfix."                             },
  { value = "sparkles",                  name = "âœ¨ Introducing new features."                    },
  { value = "pencil",                    name = "ğŸ“ Writing docs."                                },
  { value = "rocket",                    name = "ğŸš€ Deploying stuff."                             },
  { value = "lipstick",                  name = "ğŸ’„ Updating the UI and style files."             },
  { value = "tada" ,                     name = "ğŸ‰ Initial commit."                              },
  { value = "white_check_mark",          name = "âœ… Updating tests."                              },
  { value = "lock",                      name = "ğŸ”’ Fixing security issues."                      },
  { value = "apple",                     name = "ğŸ Fixing something on macOS."                   },
  { value = "penguin",                   name = "ğŸ§ Fixing something on Linux."                   },
  { value = "checkered_flag",            name = "ğŸ Fixing something on Windows."                 },
  { value = "robot",                     name = "ğŸ¤– Fixing something on Android."                 },
  { value = "green_apple",               name = "ğŸ Fixing something on iOS."                     },
  { value = "bookmark",                  name = "ğŸ”–  Releasing / Version tags."                   },
  { value = "rotating_light",            name = "ğŸš¨ Removing linter warnings."                    },
  { value = "construction",              name = "ğŸš§ Work in progress."                            },
  { value = "green_heart",               name = "ğŸ’š Fixing CI Build."                             },
  { value = "arrow_down",                name = "â¬‡ï¸ Downgrading dependencies."                    },
  { value = "arrow_up",                  name = "â¬†ï¸ Upgrading dependencies."                      },
  { value = "pushpin",                   name = "ğŸ“Œ Pinning dependencies to specific versions."   },
  { value = "construction_worker",       name = "ğŸ‘· Adding CI build system."                      },
  { value = "chart_with_upwards_trend",  name = "ğŸ“ˆ Adding analytics or tracking code."           },
  { value = "recycle",                   name = "â™»ï¸ Refactoring code."                            },
  { value = "whale",                     name = "ğŸ³ Work about Docker."                           },
  { value = "heavy_plus_sign",           name = "â• Adding a dependency."                         },
  { value = "heavy_minus_sign",          name = "â– Removing a dependency."                       },
  { value = "wrench",                    name = "ğŸ”§ Changing configuration files."                },
  { value = "globe_with_meridians",      name = "ğŸŒ Internationalization and localization."       },
  { value = "pencil2",                   name = "âœï¸ Fixing typos."                                },
  { value = "poop",                      name = "ğŸ’© Writing bad code that needs to be improved."  },
  { value = "rewind",                    name = "âª Reverting changes."                           },
  { value = "twisted_rightwards_arrows", name = "ğŸ”€ Merging branches."                            },
  { value = "package",                   name = "ğŸ“¦ Updating compiled files or packages."         },
  { value = "alien",                     name = "ğŸ‘½ Updating code due to external API changes."   },
  { value = "truck",                     name = "ğŸšš Moving or renaming files."                    },
  { value = "page_facing_up",            name = "ğŸ“„ Adding or updating license."                  },
  { value = "boom",                      name = "ğŸ’¥ Introducing breaking changes."                },
  { value = "bento",                     name = "ğŸ± Adding or updating assets."                   },
  { value = "ok_hand",                   name = "ğŸ‘Œ Updating code due to code review changes."    },
  { value = "wheelchair",                name = "â™¿ï¸  Improving accessibility."                     },
  { value = "bulb",                      name = "ğŸ’¡ Documenting source code."                     },
  { value = "beers",                     name = "ğŸ» Writing code drunkenly."                      },
  { value = "speech_balloon",            name = "ğŸ’¬ Updating text and literals."                  },
  { value = "card_file_box",             name = "ğŸ—ƒ  Performing database related changes."         },
  { value = "loud_sound",                name = "ğŸ”Š Adding logs."                                 },
  { value = "mute",                      name = "ğŸ”‡ Removing logs."                               },
  { value = "busts_in_silhouette",       name = "ğŸ‘¥ Adding contributor(s)."                       },
  { value = "children_crossing",         name = "ğŸš¸ Improving user experience / usability."       },
  { value = "building_construction",     name = "ğŸ— Making architectural changes."                },
  { value = "iphone",                    name = "ğŸ“± Working on responsive design."                },
  { value = "clown_face",                name = "ğŸ¤¡ Mocking things."                              },
  { value = "egg",                       name = "ğŸ¥š Adding an easter egg."                        },
  { value = "see_no_evil",               name = "ğŸ™ˆ Adding or updating a .gitignore file."        },
  { value = "camera_flash",              name = "ğŸ“¸ Adding or updating snapshots."                },
  { value = "alembic",                   name = "âš— Experimenting new things."                    },
  { value = "mag",                       name = "ğŸ” Improving SEO."                               },
  { value = "wheel_of_dharma",           name = "â˜¸ï¸ Work about Kubernetes."                       },
  { value = "label",                     name = "ğŸ·ï¸ Adding or updating types (Flow, TypeScript)." }
]
message = "Select the type of change you are committing"